[package]
name = "rustread"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uname-rs = "0.1.1"

[[bin]]
name = "rustread"
path = "main.rs"
